import './globals.css'
import '../public/css/main.css'
import '../public/css/conffu.css'
import Script from 'next/script'

export const metadata = {
    title: 'FABRIC-BOT',
    description: 'Generated by IT-vcentre',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" className=' w-[100vw] overflow-x-hidden'>
            <head>
                <Script
                    src="https://telegram.org/js/telegram-web-app.js"
                    strategy="beforeInteractive"
                />
                <Script
                    src="/js/taptic.js"
                    strategy="beforeInteractive"
                ></Script>
            </head>
            <body className="">
                <main className="app">{children}</main>
            </body>
        </html>
    )
}
